name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: Talocka
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 10s
          --health-retries 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        until PGPASSWORD=postgres psql -h postgres -U postgres -d Talocka -c "SELECT 1;" > /dev/null 2>&1; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Vérifier la connexion PostgreSQL
      run: |
        PGPASSWORD=postgres psql -h postgres -U postgres -d Talocka -c "SELECT 1;"

    - name: Run migrations
      env:
        DATABASE_URL: postgresql://postgres:postgres@postgres:5432/Talocka
      run: |
        cd Talocka
        python manage.py migrate

    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@postgres:5432/Talocka
        PGPASSWORD: postgres
      run: |
        cd Talocka
        python manage.py test
