name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: Talocka
        ports:
          - 5432:5432
        options: >-
          --health-interval 5s
          --health-timeout 10s
          --health-retries 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check running containers
      run: docker ps -a

    - name: Debug PostgreSQL Connection
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -c "\l" || PGPASSWORD=postgres psql -h postgres -U postgres -c "\l"

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..30}; do
          if PGPASSWORD=postgres psql -h localhost -U postgres -d Talocka -c "SELECT 1;" > /dev/null 2>&1; then
            echo "PostgreSQL is ready!"
            exit 0
          fi
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        echo "PostgreSQL did not become ready in time."
        exit 1

    - name: Run migrations
      env:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/Talocka
      run: |
        python Talocka/manage.py migrate

    - name: Create test database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE DATABASE test_db;"

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
      run: |
        python manage.py test
